// This file is auto-generated by @hey-api/openapi-ts

export const $Body_create_new_user_auth_create_user_post = {
    properties: {
        input: {
            '$ref': '#/components/schemas/CreateUser'
        },
        password: {
            type: 'string',
            title: 'Password'
        }
    },
    type: 'object',
    required: ['input', 'password'],
    title: 'Body_create_new_user_auth_create_user_post'
} as const;

export const $Body_set_access_token_auth_token_post = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_set_access_token_auth_token_post'
} as const;

export const $CreateUser = {
    properties: {
        username: {
            type: 'string',
            title: 'Username'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        first_name: {
            type: 'string',
            title: 'First Name'
        },
        last_name: {
            type: 'string',
            title: 'Last Name'
        }
    },
    type: 'object',
    required: ['username', 'email', 'first_name', 'last_name'],
    title: 'CreateUser'
} as const;

export const $HTTPValidationError = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const $ListAdd = {
    properties: {
        list_name: {
            type: 'string',
            title: 'List Name'
        },
        type: {
            type: 'string',
            title: 'Type'
        }
    },
    type: 'object',
    required: ['list_name', 'type'],
    title: 'ListAdd'
} as const;

export const $ManualAdd = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        artist: {
            type: 'string',
            title: 'Artist'
        },
        uuid: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Uuid'
        },
        lyrics: {
            type: 'string',
            title: 'Lyrics'
        }
    },
    type: 'object',
    required: ['title', 'artist', 'lyrics'],
    title: 'ManualAdd'
} as const;

export const $SpotifyAdd = {
    properties: {
        uri: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Uri'
        }
    },
    type: 'object',
    title: 'SpotifyAdd'
} as const;

export const $Token = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type'
        }
    },
    type: 'object',
    required: ['access_token', 'token_type'],
    title: 'Token'
} as const;

export const $ValidationError = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const $WordAdd = {
    properties: {
        word: {
            type: 'string',
            title: 'Word'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        artist: {
            type: 'string',
            title: 'Artist'
        },
        list_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'List Id'
        }
    },
    type: 'object',
    required: ['word', 'title', 'artist'],
    title: 'WordAdd'
} as const;