// This file is auto-generated by @hey-api/openapi-ts

export type Body_create_new_user_auth_create_user_post = {
    input: CreateUser;
    password: string;
};

export type Body_set_access_token_auth_token_post = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CreateUser = {
    username: string;
    email: string;
    first_name: string;
    last_name: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ListAdd = {
    list_name: string;
    type: string;
};

export type ManualAdd = {
    title: string;
    artist: string;
    uuid?: (string | null);
    lyrics: string;
};

export type SpotifyAdd = {
    uri?: (string | null);
};

export type Token = {
    access_token: string;
    token_type: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type WordAdd = {
    word: string;
    title: string;
    artist: string;
    list_id?: (string | null);
};

export type RootGetResponse = (unknown);

export type RootGetError = unknown;

export type GetCurrentCaregiverUsersGetResponse = (unknown);

export type GetCurrentCaregiverUsersGetError = unknown;

export type ReadUsersMeAuthCurrentUserGetResponse = (unknown);

export type ReadUsersMeAuthCurrentUserGetError = unknown;

export type CreateNewUserAuthCreateUserPostData = {
    body: Body_create_new_user_auth_create_user_post;
};

export type CreateNewUserAuthCreateUserPostResponse = (unknown);

export type CreateNewUserAuthCreateUserPostError = (HTTPValidationError);

export type SetAccessTokenAuthTokenPostData = {
    body: Body_set_access_token_auth_token_post;
};

export type SetAccessTokenAuthTokenPostResponse = (Token);

export type SetAccessTokenAuthTokenPostError = (HTTPValidationError);

export type AddSongSpotSongAddSongSpotPostData = {
    body?: (SpotifyAdd);
};

export type AddSongSpotSongAddSongSpotPostResponse = (unknown);

export type AddSongSpotSongAddSongSpotPostError = (HTTPValidationError);

export type AddSongManualSongAddSongManualPostData = {
    body: ManualAdd;
};

export type AddSongManualSongAddSongManualPostResponse = (unknown);

export type AddSongManualSongAddSongManualPostError = (HTTPValidationError);

export type GetSongSongGetSongGetData = {
    query?: {
        artist?: string;
        title?: string;
    };
};

export type GetSongSongGetSongGetResponse = (unknown);

export type GetSongSongGetSongGetError = (HTTPValidationError);

export type GetWordSongGetWordGetData = {
    query?: {
        idseq?: string;
    };
};

export type GetWordSongGetWordGetResponse = (unknown);

export type GetWordSongGetWordGetError = (HTTPValidationError);

export type GetSongsSongGetSongsGetResponse = (unknown);

export type GetSongsSongGetSongsGetError = unknown;

export type GetGlobalSongsSongGetGlobalSongsGetData = {
    query?: {
        limit?: number;
        offset?: number;
    };
};

export type GetGlobalSongsSongGetGlobalSongsGetResponse = (unknown);

export type GetGlobalSongsSongGetGlobalSongsGetError = (HTTPValidationError);

export type GetListsListsGetListsGetResponse = (unknown);

export type GetListsListsGetListsGetError = unknown;

export type AddListListsAddListPostData = {
    body: ListAdd;
};

export type AddListListsAddListPostResponse = (unknown);

export type AddListListsAddListPostError = (HTTPValidationError);

export type DeleteListListsDeleteListDeleteData = {
    query: {
        list_id: string;
    };
};

export type DeleteListListsDeleteListDeleteResponse = (unknown);

export type DeleteListListsDeleteListDeleteError = (HTTPValidationError);

export type GetAlistListsGetAlistGetData = {
    query: {
        list_id: string;
    };
};

export type GetAlistListsGetAlistGetResponse = (unknown);

export type GetAlistListsGetAlistGetError = (HTTPValidationError);

export type GetTypeListsListsGetTypeListsGetData = {
    query: {
        type: string;
    };
};

export type GetTypeListsListsGetTypeListsGetResponse = (unknown);

export type GetTypeListsListsGetTypeListsGetError = (HTTPValidationError);

export type CheckAllListsListsCheckAllListsGetData = {
    query: {
        type: string;
        word: string;
    };
};

export type CheckAllListsListsCheckAllListsGetResponse = (unknown);

export type CheckAllListsListsCheckAllListsGetError = (HTTPValidationError);

export type DeleteWordListsDeleteWordDeleteData = {
    query: {
        list_id: string;
        word: string;
    };
};

export type DeleteWordListsDeleteWordDeleteResponse = (unknown);

export type DeleteWordListsDeleteWordDeleteError = (HTTPValidationError);

export type AddWordListsAddWordPostData = {
    body: WordAdd;
};

export type AddWordListsAddWordPostResponse = (unknown);

export type AddWordListsAddWordPostError = (HTTPValidationError);

export type GetWordDataListsGetWordDataGetData = {
    query: {
        value: string;
    };
};

export type GetWordDataListsGetWordDataGetResponse = (unknown);

export type GetWordDataListsGetWordDataGetError = (HTTPValidationError);